"""Generate figures and appendix table for Section 5.1 Parte I.

Outputs:
  - outputs/charts/parte1_cross_testing.png  (2x2 causal graphs)
  - outputs/parte1_apendice_tabla.tex        (LaTeX table with 24 configs)
"""
from __future__ import annotations

import json

import matplotlib.pyplot as plt

from helpers import CHARTS_DIR, OUTPUTS_DIR, draw_causal_graph
from pipeline import run_causality
from run_e4_subsets import SUBSETS

INDEX_START = "1993-01-01"

# 4 configs to display in Figure 2 (2x2 grid)
FIG2_PANELS = [
    ("A", "A_bollerslev", "DIA"),
    ("B", "C_lopezdeprado", "SPY"),
    ("C", "B_kelly", "DIA"),
    ("D", "C_lopezdeprado", "IWM"),
]


def load_or_run(subset_name, ticker):
    cfg = SUBSETS[subset_name]
    start = "1993-01-29" if ticker == "SPY" else INDEX_START
    res, _ = run_causality(
        ticker, weighted_pe=False, tag=f"e5_pe_{subset_name}_{ticker}",
        start=start, add_future_return=True,
        factors_filter=cfg["factors"],
        include_vix=cfg["include_vix"],
        include_ltrevrsl=cfg["include_ltrevrsl"],
    )
    return res, cfg


def generate_fig2():
    print("Generating Figure 2 (2x2 cross-testing causal graphs)...")
    panels = []
    for label, subset_name, ticker in FIG2_PANELS:
        res, cfg = load_or_run(subset_name, ticker)
        print(f"  Panel {label}: {subset_name} / {ticker}  n={res.n_obs}")
        panels.append((label, subset_name, ticker, res, cfg))

    fig, axes = plt.subplots(2, 2, figsize=(16, 14))
    axes = axes.flatten()
    for ax, (label, subset_name, ticker, res, cfg) in zip(axes, panels):
        title = f"Panel {label}: {ticker} · Subset {subset_name.split('_')[0]} ({cfg['size']} factores)"
        draw_causal_graph(ax, title, res.mean_adj, res.labels,
                          edge_prob=res.edge_prob, target="FutureReturn")
    fig.suptitle("Cross-testing E5: cuatro configuraciones seleccionadas (variante PE)",
                 fontsize=14, fontweight="bold")
    plt.tight_layout(rect=[0, 0.02, 1, 0.96])
    out_path = CHARTS_DIR / "parte1_cross_testing.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {out_path}")


def _fmt_pct(x):
    return f"{100*x:.0f}\\%"


def _fmt_edges(edges, max_display=3):
    if not edges:
        return "--"
    parts = []
    for e in edges[:max_display]:
        s = e["source"] if "source" in e else "?"
        t = e["target"] if "target" in e else "?"
        p = e.get("edge_prob", 0)
        parts.append(f"{s}$\\to${t} ({_fmt_pct(p)})")
    if len(edges) > max_display:
        parts.append(f"\\ldots ({len(edges) - max_display} más)")
    return "; ".join(parts)


def generate_appendix_table():
    print("Generating appendix table (24 configs)...")
    data = json.load(open("outputs/results.json"))
    grid = data["e5_grid"]

    rows = []
    for subset_name in ["A_bollerslev", "B_kelly", "C_lopezdeprado"]:
        subset_short = subset_name.split("_")[0]
        for ticker in ["SPY", "QQQ", "IWM", "DIA"]:
            g = grid[f"{subset_name}__{ticker}"]
            for variant in ["pe", "wpe"]:
                disc = "\\checkmark" if g[f"{variant}_disconnected"] else "\\ding{55}"
                fr_causes = g[f"{variant}_future_causes"]
                fr_str = ", ".join(fr_causes) if fr_causes else "--"
                ent_edges = g[f"{variant}_entropy_edges"]
                edges_str = _fmt_edges(ent_edges, max_display=2)
                n = g[f"{variant}_n_obs"]
                rows.append((
                    subset_short, ticker, variant.upper(),
                    n, disc, fr_str, edges_str
                ))

    lines = [
        r"% Auto-generated by generate_parte1_figures.py",
        r"\begin{table}[H]",
        r"  \centering",
        r"  \small",
        r"  \begin{tabular}{llcrccp{5.5cm}}",
        r"    \toprule",
        r"    Subset & Índice & Var. & $n_{\text{obs}}$ & Desc. & Causa robusta de FR & Edges robustos de Entropy \\",
        r"    \midrule",
    ]
    prev_subset = None
    for subset, ticker, var, n, disc, fr, edges in rows:
        prefix = subset if subset != prev_subset else ""
        lines.append(f"    {prefix} & {ticker} & {var} & {n} & {disc} & {fr} & {edges} \\\\")
        prev_subset = subset
    lines += [
        r"    \bottomrule",
        r"  \end{tabular}",
        r"  \caption{Detalle completo de las 24 configuraciones del sub-experimento E5 (cross-product). ",
        r"    \emph{Desc.}: si la entropía está estructuralmente desconectada (sin edges robustos con probabilidad bootstrap $\geq 0.5$). ",
        r"    \emph{Causa robusta de FR}: factores con edge robusto hacia FutureReturn. ",
        r"    \emph{Edges robustos de Entropy}: aristas robustas entrantes o salientes del nodo Entropy.}",
        r"  \label{tab:e5-full}",
        r"\end{table}",
    ]

    out_path = OUTPUTS_DIR / "parte1_apendice_tabla.tex"
    out_path.write_text("\n".join(lines))
    print(f"  -> {out_path}")


if __name__ == "__main__":
    generate_fig2()
    generate_appendix_table()
    print("\nDone.")
